export const SIGN_IN = 'SIGN_IN';
export const SIGN_UP = 'SIGN_UP';
export const AUTO_SIGN_IN = 'AUTO_SIGN_IN';
export const SIGN_IN_WITH_FACEBOOK = 'SIGN_IN_WITH_FACEBOOK';
export const SIGN_IN_WITH_GOOGLE ='SIGN_IN_WITH_GOOGLE';
export const SEND_RESET_PASSWORD_MAIL ='SEND_RESET_PASSWORD_MAIL';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';

export const FIND_USER_ORDERS = 'FIND_USER_ORDERS';
export const ADD_USER_ORDER = 'ADD_USER_ORDER';
export const FIND_ORDER = 'FIND_ORDER';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const REGISTER_FOR_PUSH_NOTIFICATIONS = 'REGISTER_FOR_PUSH_NOTIFICATIONS';
